language: python
cache: pip

matrix:
  include:
    - env: TOXENV="py34-dj{110,111,20,21}"
      python: '3.4'
    - env: TOXENV="py35-dj{110,111,20,21}"
      python: '3.5'
    - env: TOXENV="py36-dj{110,111,20,21}"
      python: '3.6'
    - env: TOXENV="py37-dj{110,111,20,21}"
      python: '3.7'
    - env: |
        TOXENV="py37-dj{111,20,21}-postgres"
        DATABASE_URL="postgres://postgres@localhost/database"
      python: '3.7'
      services:
        - postgresql
    - env: |
        TOXENV="py37-dj{111,20,21}-mysql"
        DATABASE_URL="mysql://travis@127.0.0.1/database"
      python: '3.7'
      services:
        - mysql
    - env: TOXENV="flake8,isort,docs"
      python: '3.7'

install:
  - pip install --upgrade pip wheel tox

script:
  - env
  - tox
